### ISSUE TITLE
Yukon timezone isn't sorted by UTC time in the timezone using GetDisplayNames

### ISSUE THREAD

**Issue by dlobrino** [mattjohnsonpint/TimeZoneNames#72]
In version 4.2.0.0, When using IDictionary<string, string> GetDisplayNames(string languageCode, bool useIanaZoneIds = false) in TZNames. The output data is not sorted properly, UTC-7:00 Yukon located between UTC-9:00 and UTC-8:00.
Using variations: en-US and useIanaZoneIds = true
Tested using .net 5

**Comment by mattjohnsonpint** [comment]
This was fixed in 6.0.0.

Snapshot test here:

https://github.com/mattjohnsonpint/TimeZoneNames/blob/c295e8f6198a4332cbb19997e3c461c0557048a8/test/TimeZoneNames.Tests/Verify/DisplayNamesTests/CanGetDisplayNames_IanaZones/DisplayNamesTests.CanGetDisplayNames_IanaZones_language%3Den_US.verified.txt#L14-L16
