### ISSUE TITLE
Incorrect offset for Volgograd Timezone

### ISSUE THREAD

**Issue by mateuszrozanski** [mattjohnsonpint/TimeZoneNames#89]
Hi. 
For _en-US_ language code, method _GetDisplayNames_ returns Volgograd timezone with incorrect offset. It should have offset UTC +3:00 instead of the current one UTC +4:00. Could you fix that ?

![image](https://user-images.githubusercontent.com/26851593/214817601-11d14e55-18bc-49df-ac75-5e480d8c276c.png)

**Comment by mattjohnsonpint** [comment]
Hi.  This was already fixed in 6.0.0.  Are you on an older version?

There's a snapshot test here for it:

https://github.com/mattjohnsonpint/TimeZoneNames/blob/c295e8f6198a4332cbb19997e3c461c0557048a8/test/TimeZoneNames.Tests/Verify/DisplayNamesTests/CanGetDisplayNames_IanaZones/DisplayNamesTests.CanGetDisplayNames_IanaZones_language%3Den_US.verified.txt#L78
